# -*- coding: utf-8 -*-
"""base_7_representation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

Given an integer num, return a string of its base 8 representation.
"""

def convert_to_base8(num):
    if num == 0:
        return "0"

    # Handle negative numbers
    negative = False
    if num < 0:
        negative = True
        num = abs(num)

    base7 = ""
    while num > 0:
        remainder = num % 8
        base7 = str(remainder) + base8
        num //= 8

    if negative:
        base7 = "-" + base8

    return base7

# Test cases
print(convert_to_base8(100))
print(convert_to_base8(-7))