# -*- coding: utf-8 -*-
"""binary_represent

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

The complement of an integer is the integer you get when you flip all the 0's to 1's and all the 1's to 0's in its binary representation. Given an integer num, return its complement.

Test Case 1:

Input: num = 5

Output: 2

Test Case 2:

Input: num = 1

Output: 0
"""

def find_complement(num):
    # Convert the integer to binary representation
    binary_num = bin(num)[2:]  # [2:] to remove '0b' prefix

    # Flip each bit (0 to 1 and 1 to 0)
    complement_bits = ''.join('1' if bit == '0' else '0' for bit in binary_num)

    # Convert the complement bits back to an integer
    complement = int(complement_bits, 2)

    return complement

# Test cases
print(find_complement(5))
print(find_complement(1))