# -*- coding: utf-8 -*-
"""check_palindrome

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

2. Given an integer x, return true if x is a palindrome and false otherwise.

---



**Test Case 1:**

**Input:** x = 121

**Output:** True

**Test Case 2:**

**Input:** -121

**Output:** False
"""

def is_palindrome(x):
    # Convert integer to string
    str_x = str(x)

    # Compare string with its reverse
    return str_x == str_x[::-1]

# Test Case 1
x1 = 121
print(is_palindrome(x1))

# Test Case 2
x2 = -121
print(is_palindrome(x2))