# -*- coding: utf-8 -*-
"""lenth_of_last_word

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

Given a string s consisting of words and spaces, return the length of the last word in the string. A word is a maximal substring consisting of non-space characters only.

**Test Case 1: **

**Input:** s = “Hello World”

**Output:** 5

**Test Case 2:**

**Input:** s = “ fly me to the moon ”

**Output:** 4
"""

def lengthOfLastWord(s: str) -> int:
    # Strip trailing spaces
    s = s.rstrip()
    # Find the index of the last space
    last_space_index = s.rfind(' ')
    # Return the length of the last word
    return len(s) - last_space_index - 1 if last_space_index != -1 else len(s)

# Test Case 1
s1 = "Hello World"
print(lengthOfLastWord(s1))

# Test Case 2
s2 = "fly me to the moon"
print(lengthOfLastWord(s2))