# -*- coding: utf-8 -*-
"""max_consecutives

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

Given a binary array nums, return the maximum number of consecutive 1's in the array.

Test Case 1:

Input: nums = [1,1,0,1,1,1]

Output: 3

Test Case 2:

Input: nums = [1,0,1,1,0,1]

Output: 2
"""

def find_max_consecutive_ones(nums):
    max_count = 0
    count = 0

    for num in nums:
        if num == 1:
            count += 1
            max_count = max(max_count, count)
        else:
            count = 0

    return max_count

# Test cases
print(find_max_consecutive_ones([1, 1, 0, 1, 1, 1]))
print(find_max_consecutive_ones([1, 0, 1, 1, 0, 1]))