# -*- coding: utf-8 -*-
"""max_consecutives

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qiSVRD1fuasel8Pd97kV8WGyCfHEGUxp

Given an integer num, return a string of its base 7 representation.

Test Case 1:

Input: num = 100

Output: “202”

Test Case 2:

Input: num = -7

Output: “-10”
"""

def convert_to_base7(num):
    if num == 0:
        return "0"

    # Handle negative numbers
    negative = False
    if num < 0:
        negative = True
        num = abs(num)

    base7 = ""
    while num > 0:
        remainder = num % 7
        base7 = str(remainder) + base7
        num //= 7

    if negative:
        base7 = "-" + base7

    return base7

# Test cases
print(convert_to_base7(100))
print(convert_to_base7(-7))